//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.AdditionalServices = new HashSet<AdditionalServices>();
        }
    
        public int IDOrder { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<int> IDWorker { get; set; }
        public Nullable<int> IDClient { get; set; }
        public string Status { get; set; }
        public string Cost { get; set; }
        public Nullable<System.DateTime> DateNTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalServices> AdditionalServices { get; set; }
        public virtual Client Client { get; set; }
        public virtual Product Product { get; set; }
        public virtual Worker1 Worker1 { get; set; }
    }
}
